version: '3.9'

services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt_broker
    restart: always
    ports:
      - "1883:1883"
    env_file:
      - .env
    volumes:
      - "./mosquitto_config:/mosquitto/config"

  relay:
    image: ghcr.io/agridata-trade/robonomics-relay:main
    container_name: robonomics_mqtt_broker
    restart: always
    env_file:
      - .env
    depends_on:
      - mqtt

  db:
    image: timescale/timescaledb-ha:pg13-latest
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db

  api:
    image: ghcr.io/agridata-trade/api:main
    container_name: api
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres:
    name: agridata_db
