version: '3.6'

services:
  mqtt:
    image: eclipse-mosquitto:2
    restart: always
    ports:
      - "1883:1883"
    env_file:
      - .env
    volumes:
      - "./mosquitto_config:/mosquitto/config"

  relay:
    image: ghcr.io/agridata-trade/robonomics-relay:main
    restart: always
    env_file:
      - .env
    depends_on:
      - mqtt
      - db

  db:
    image: timescale/timescaledb-ha:pg13-latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    image: ghcr.io/agridata-trade/api:main
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres:
    name: agridata_db
